### ISSUE TITLE
Password for ssh'ing into root

### ISSUE THREAD

**Issue by TableBookspro** [BlakeBeus/vagrant-ubuntu16.4-LEMP-provision-script#1]
I am trying to use this to build a LEMP vagrant box with Ubuntu 16. Am I missing something? After building the box, I try to ssh in using ssh root@BOXNAME and I get a password prompt. Is a default set. I have tried a few different choices, including the SQL ones listed in the config files, but they do not work. Thanks for building this out by the way.

**Comment by TableBookspro** [comment]
whoops my bad, I should have been running `vagrant ssh`, my bad.

**Comment by BlakeBeus** [comment]
Nice!  Glad you got it figured out.
